// Generated by CoffeeScript 1.6.3
(function() {
  var fs, log, main, syntax;

  fs = require('fs');

  syntax = function() {
    console.log("Syntax: loopscript file.loopscript outputFilename [optional sound name]");
    console.log("\n        Sound name defaults to the last sound defined in the LoopScript.");
    return process.exit(1);
  };

  log = function(text) {
    return console.log("LS: " + text);
  };

  main = function() {
    var args, inputFilename, loopscript, outputFilename, script, which;
    args = process.argv.slice(2);
    if (args.length < 2 || args.length > 3) {
      syntax();
    }
    which = null;
    inputFilename = args[0];
    outputFilename = args[1];
    if (args.length > 2) {
      which = args[2];
    }
    log("Reading " + inputFilename);
    script = fs.readFileSync(inputFilename, {
      encoding: 'utf-8'
    });
    loopscript = require("./loopscript");
    loopscript.render({
      script: script,
      log: log,
      outputFilename: outputFilename,
      which: which,
      readLocalFiles: true
    });
    return log("Wrote " + outputFilename);
  };

  module.exports = {
    main: main
  };

}).call(this);
