// Generated by CoffeeScript 1.8.0
(function() {
  var fs, log, main, syntax, verboseMode;

  fs = require('fs');

  verboseMode = false;

  syntax = function() {
    console.error("Syntax: loopscript [-v] file.loopscript outputFilename [sound name]\n");
    console.error("        Sound name defaults to the last sound defined in the LoopScript.");
    console.error("        -h,--help         This help output");
    console.error("        -v,--verbose      Verbose output");
    return process.exit(1);
  };

  log = {
    verbose: function(text) {
      if (verboseMode) {
        return console.log(text);
      }
    },
    error: function(text) {
      return console.error("ERROR: " + text);
    }
  };

  main = function() {
    var args, inputFilename, loopscript, script, wavFilename, which;
    args = require('minimist')(process.argv.slice(2), {
      boolean: ['h', 'v'],
      alias: {
        help: 'h',
        verbose: 'v'
      }
    });
    if (args.help || args._.length < 2 || args._.length > 3) {
      syntax();
    }
    which = null;
    inputFilename = args._[0];
    wavFilename = args._[1];
    if (args._.length > 2) {
      which = args._[2];
    }
    verboseMode = args.v;
    log.verbose("Reading " + inputFilename);
    script = fs.readFileSync(inputFilename, {
      encoding: 'utf-8'
    });
    loopscript = require("./loopscript");
    loopscript.render({
      script: script,
      log: log,
      wavFilename: wavFilename,
      which: which,
      readLocalFiles: true
    });
    return log.verbose("Wrote " + wavFilename);
  };

  module.exports = {
    main: main
  };

}).call(this);
